approvedGitRepositories:
  - '**'

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

supportedArchitectures:
  cpu:
    - arm
    - arm64
    - ia32
    - loong64
    - mips
    - mipsel
    - ppc64
    - riscv64
    - s390
    - s390x
    - x64
    - wasm32
  os:
    - current
    - darwin
    - linux
    - win32
