compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - 'arm'
    - 'arm64'
    - 'ia32'
    - 'loong64'
    - 'mips'
    - 'mipsel'
    - 'ppc64'
    - 'riscv64'
    - 's390'
    - 's390x'
    - 'x64'
    - 'wasm32'
  os:
    - 'current'
    - 'darwin'
    - 'linux'
    - 'win32'
